<?php $_config_vars = array (
  'title' => 'Alat X!',
  'source' => 'Lihat Sumber',
  'language' => 'Pilih bahasa',
  'tool' => 'Penghitung suntingan milik X!',
  'submit' => 'Kirim',
  'nowiki' => '$1 bukanlah wiki yang sah',
  'welcome' => 'Selamat datang ke penghitung suntingan milik X!',
  'username' => 'Nama pengguna',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Kesalahan MySQL, tolong laporkan ke X! menggunakan <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>pelapor kesalahan.</a> Pastikan untuk melaporkan kesalahan SQL berikut ketika pelaporan: <br /><pre>$1</pre>',
  'nosuchuser' => '$1 tidak ada.',
  'highreplag' => 'Perhatian: <a href=\'https://wiki.toolserver.org/view/Replag\'>Lag replikasi</a> tinggi, perubahan lebih baru dari $1 dapat tidak ditampilkan.',
  'mainspace' => 'Artikel',
  'generalinfo' => 'Info umum pengguna',
  'groups' => 'Kelompok pengguna',
  'firstedit' => 'Suntingan pertama',
  'unique' => 'Suntingan artikel unik',
  'average' => 'Rata- rata suntingan per halaman',
  'total' => 'Total suntingan (termasuk yang dihapus)',
  'deleted' => 'Suntingan yang telah dihapus',
  'live' => 'Suntingan hidup',
  'namespacetotals' => 'Total ruang nama',
  'monthcounts' => 'Perhitungan bulan',
  'topedited' => 'Artikel tersering disunting',
  'executed' => 'Dieksekusi dalam $1 detik',
  'graphalt' => 'Grafik total ruang nama',
  'viewingsource' => 'Melihat sumber $1',
  'sourceviewer' => 'Sumber dari Penghitung Suntingan milik Soxred93',
  'translation' => 'Penerjemah Penghitung Suntingan milik Soxred93',
  'submitted' => 'Telah dikirim. Terima kasih !',
  'nograph' => 'Pengguna belum tendaftar. Jika Anda ingin melihat grafik, silakan membuat halaman <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> dengan isi apapun. Alternatif lain, Anda dapat membuat halaman <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> untuk terdaftar di seluruh wiki Wikimedia.',
  'notopedit' => 'Maaf, tetapi untuk mengonsumsi sumber daya yang wajar dari Toolserver, Artikel yang Paling Sering Disunting dinonaktifkan untuk pengguna dengan lebih dari 45.000 suntingan.',
  'translatelink' => 'terjemahkan',
  'edits' => 'suntingan',
  'file' => 'Berkas',
  'show' => 'tampilkan',
  'hide' => 'sembunyikan',
  'selectfile' => 'Pilih berkas untuk dilihat',
  'w' => 'minggu',
  'd' => 'hari',
  'h' => 'jam',
  'm' => 'menit',
  's' => 'detik',
); ?>