<?php $_config_vars = array (
  'title' => 'Ferramentas X!',
  'source' => 'Ver código',
  'language' => 'Selecione um idioma',
  'tool' => 'Contador de edições X!',
  'submit' => 'Enviar',
  'nowiki' => '$1 não é uma wiki válida',
  'welcome' => 'Bem-vindo ao contador de edições X!',
  'username' => 'Nome de usuário',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Erro MySQL, por favor, reporte para X! usando <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>o reportador de erros.</a> Esteja certo de reportar o seguinte erro SQL:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 não existe.',
  'highreplag' => 'Aviso: <a href=\'https://wiki.toolserver.org/view/Replag\'>O lag</a> está alto, mudanças mais recentes que $1 podem não ser exibidos.',
  'mainspace' => 'Artigo',
  'generalinfo' => 'Informações de usuário gerais',
  'groups' => 'Grupos de usuário',
  'firstedit' => 'Primeira edição',
  'unique' => 'Artigos únicos editados',
  'average' => 'Média de edições por página',
  'total' => 'Total de edições (incluindo eliminadas)',
  'deleted' => 'Edições eliminadas',
  'live' => 'Edições não eliminadas',
  'namespacetotals' => 'Total por namespace',
  'monthcounts' => 'Contagem mensal',
  'topedited' => 'Artigos mais editados',
  'executed' => 'Executado em $1 segundos',
  'graphalt' => 'Total por namespace - gráfico de pizza',
  'viewingsource' => 'Vendo fonte de $1',
  'sourceviewer' => 'Fonte do contador de edições Soxred93',
  'translation' => 'Tradutor do Contador de Edições Soxred93\'s',
  'submitted' => 'Enviado. Obrigado!',
  'nograph' => 'O usuário ainda não habilitou esta função. Se você  quer ver os gráficos, por favor crie <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> com qualquer conteúdo. De forma alternativa, você pode criar <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> para habilitar a função a todas as wikis Wikimedia.',
  'notopedit' => 'Desculpe, mas para consumir apenas minha parte justa nos recursos do toolserver, os Artigos Mais Editados são desabilitados para usuários com mais de 45000 edições.',
  'translatelink' => 'traduzir',
  'edits' => 'edições',
  'file' => 'Arquivo',
  'show' => 'mostrar',
  'hide' => 'esconder',
  'selectfile' => 'Selecione um arquivo para visualizar:',
  'w' => 'semanas',
  'd' => 'dias',
  'h' => 'horas',
  'm' => 'minutos',
  's' => 'segundos',
); ?>