<?php $_config_vars = array (
  'title' => 'Các công cụ của X!',
  'source' => 'Xem mã nguồn',
  'language' => 'Chọn một ngôn ngữ',
  'tool' => 'Công cụ Đếm sửa đổi của X!',
  'submit' => 'Gửi',
  'nowiki' => '$1 không phải là wiki hợp lệ',
  'welcome' => 'Chào mừng đến công cụ đếm sửa đổi của X!',
  'username' => 'Tên người dùng',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Lỗi MySQL, hãy gửi báo cáo đến X! sử dụng <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>mẫu báo lỗi.</a> Hãy chắc chắn bạn đang báo cáo lỗi SQL sau:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 không tồn tại.',
  'highreplag' => 'Cảnh báo: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> cao, những thay đổi mới hơn $1 có thể sẽ không được hiển thị.',
  'mainspace' => 'Bài viết',
  'generalinfo' => 'Thông tin chung',
  'groups' => 'Nhóm người dùng',
  'firstedit' => 'Lần sửa đầu',
  'unique' => 'Số bài viết có sửa đổi chính',
  'average' => 'Số sửa đổi trung bình trên một trang',
  'total' => 'Tổng số sửa đổi (bao gồm đã bị xoá)',
  'deleted' => 'Sửa đổi bị xoá',
  'live' => 'Sửa đổi còn sống',
  'namespacetotals' => 'Trên toàn bộ không gian tên',
  'monthcounts' => 'Số sửa đổi tháng',
  'topedited' => 'Trang sửa đổi nhiều nhất',
  'executed' => 'Quá trình mất $1 giây',
  'graphalt' => 'Biểu đồ quạt trên toàn bộ không gian tên',
  'viewingsource' => 'Xem mã nguồn bài $1',
  'sourceviewer' => 'Mã nguồn Công cụ Đếm Sửa đổi của Soxred93',
  'translation' => 'Dịch công cụ đếm của Soxred93',
  'submitted' => 'Đã gửi. Cảm ơn',
  'nograph' => 'Người dùng chưa tham gia. Nếu bạn muốn xem biểu đồ, hãy tạo <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> với bất kì nội dung gì. Ngoài ra, bạn có thể tạo <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> để xem trên tất cả wiki của Wikimedia.',
  'notopedit' => 'Xin lỗi, để chia sẻ hợp lí tài nguyên của toolserver, Bài sửa đổi nhiều nhất đã bị vô hiệu hoá với những người dùng có trên 45000 sửa đổi.',
  'translatelink' => 'dịch',
  'edits' => 'sửa đổi',
  'file' => 'Tệp',
  'show' => 'hiện',
  'hide' => 'ẩn',
  'selectfile' => 'Chọn một tệp để xem',
  'w' => 'tuần',
  'd' => 'ngày',
  'h' => 'giờ',
  'm' => 'phút',
  's' => 'giây',
  'million' => 'Thật khó tin, công cụ đếm sửa đổi này được tạo ra tháng 12 năm 2008, và trong vòng chưa đến 1,5 năm, đã được sử dụng trên <span style=\'color:red;\'>1 Triệu Lượt</span>. Thật đáng ngạc nhiên. Tôi cảm ơn mọi người vì đã sử dụng công cụ này trong thời gian qua. Nếu không có bạn, công cụ này đã không tồn tại. Hãy cùng hi vọng cho một triệu lượt khác! --X! 14 tháng 5 năm 2010',
); ?>