<?php $_config_vars = array (
  'tool' => 'X!\'s エディット・カウンター',
  'welcome' => 'X!\'s エディット・カウンターへようこそ!',
  'username' => '利用者名',
  'nosuchuser' => '$1 という名前の利用者名は存在しません',
  'mainspace' => '記事',
  'generalinfo' => 'General user info',
  'groups' => '利用者グループ',
  'firstedit' => '最初の編集',
  'unique' => '編集したページの数',
  'average' => '一ページあたりの平均編集回数',
  'total' => '総編集回数 (削除された編集も含む)',
  'deleted' => '削除された編集',
  'live' => '残っている編集',
  'namespacetotals' => '名前空間別の編集回数',
  'monthcounts' => '月別の編集回数',
  'topedited' => '編集回数が最も多いページ',
  'graphalt' => 'Namespace Totals Pie Chart',
  'viewingsource' => 'Viewing source for $1no',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => '投稿完了しました. ありがとう！',
  'nograph' => 'グラフは出力されません。グラフを利用したい場合、<a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> に何か内容を書き込んでください。この代わりに<a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a>を作成することで、WikimediaのWikiの統計全てでグラフを利用することが出来ます。',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'edits' => '回',
  'file' => 'ファイル',
  'show' => '表示',
  'hide' => '隠す',
  'selectfile' => '表示するファイルを選んでください:',
  'million' => 'Unbelievable. Absolutely unbelievable. This edit counter was created in December 2008, and in under 1.5 years, has amassed over <span style=\'color:red;\'>1 Million Hits</span>. This is astounding. I thank everyone for their continued support of this tool throughout the years. Without your support, this tool would not be in existence. Let\'s hope for another million! --X! 14 May 2010',
); ?>