<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'Quelltext betrachten',
  'language' => 'Sprache auswählen',
  'submit' => 'Absenden',
  'nowiki' => '$1 ist kein korrektes Wiki',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL Fehler, bitte an X! melden mit <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>dem Fehler-Melder.</a> Bitte sicher gehen, dass der folgende SQL Fehler genannt wird dabei:<br /><pre>$1</pre>',
  'highreplag' => 'Achtung: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replag</a> ist hoch, Änderungen neuer als $1 werden nicht angezeigt.',
  'executed' => 'In $1 Sekunden ausgeführt',
  'translatelink' => 'Übersetzung',
  'w' => 'Wochen',
  'd' => 'Tage',
  'h' => 'Stunden',
  'm' => 'Minuten',
  's' => 'Sekunden',
); ?>