<?php $_config_vars = array (
  'title' => 'Outils de X!',
  'source' => 'Voir un chef-d\'œuvre',
  'language' => 'Sélectionnez une langue',
  'tool' => 'X!\'s Edit Counter',
  'submit' => 'Envoyer',
  'nowiki' => '$1 n\'est pas un wiki valide',
  'welcome' => 'Bienvenue sur le compteur d\'éditions de X! !',
  'username' => 'Nom d\'utilisateur',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Erreur MySQL, merci d\'informer X! sur <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>la page dédiée.</a> N\'oubliez pas d\'indiquer l\'erreur SQL suivante :<br /><pre>$1</pre>',
  'nosuchuser' => 'Cet utilisateur ($1) n\'existe pas.',
  'highreplag' => 'Attention : le <a href=\'https://wiki.toolserver.org/view/Replag\'>délai de réplication</a> est élevé, les modifications de moins de $1 ne sont pas prises en compte.',
  'mainspace' => 'Principal',
  'generalinfo' => 'Informations générales sur l\'utilisateur',
  'groups' => 'Groupes de l\'utilisateur',
  'firstedit' => 'Première édition',
  'unique' => 'Nombre d\'articles différents édités',
  'average' => 'Nombre moyen d\'éditions par page',
  'total' => 'Total des modifications (incluant celles supprimées)',
  'deleted' => 'Modifications supprimées',
  'live' => 'Modifications non supprimées',
  'namespacetotals' => 'Totaux par espaces de noms',
  'monthcounts' => 'Comptes par mois',
  'topedited' => 'Articles les plus modifiés',
  'executed' => 'Exécuté en $1 secondes',
  'graphalt' => 'Camembert des totaux par espaces de noms',
  'viewingsource' => 'Affichage de la source de $1',
  'sourceviewer' => 'Source du compteur d\'éditions de Soxred93',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => 'Soumis. Merci !',
  'nograph' => 'Cet utilisateur ne s\'est pas encore inscrit. Pour voir les graphiques, créez <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> (le contenu n\'a pas d\'importance). Vous pouvez aussi créer <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> pour vous inscrire pour tous les wikis de Wikimedia.',
  'notopedit' => 'Désolé, mais pour réduire les ressources utilisées sur le toolserver, les articles les plus utilisés sont désactivés pour les utilisateurs avec plus de 45 000 modifications.',
  'translatelink' => 'traduire',
  'edits' => 'modifications',
  'file' => 'Fichier',
  'show' => 'afficher',
  'hide' => 'masquer',
  'selectfile' => 'Sélectionnez un fichier à afficher :',
  'w' => 'semaines',
  'd' => 'jours',
  'h' => 'heures',
  'm' => 'minutes',
  's' => 'secondes',
); ?>