<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'הצג מקור',
  'language' => 'בחר שפה',
  'tool' => 'X!\'s Edit Counter',
  'submit' => 'שלח',
  'nowiki' => '$1 אינו ויקי תקני',
  'welcome' => 'Welcome to X!\'s edit counter!',
  'username' => 'שם משתמש',
  'wiki' => 'ויקי',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'nosuchuser' => 'משתמש $1 לא קיים.',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mainspace' => 'מרחב ראשי',
  'generalinfo' => 'מידע כללי',
  'groups' => 'הרשאות',
  'firstedit' => 'עריכה ראשונה',
  'unique' => 'ערכים שונים שערך המשתמש',
  'average' => 'ממוצע עריכות לדף',
  'total' => 'כל העריכות (כולל כאלה שנמחקו)',
  'deleted' => 'עריכות שנמחקו',
  'live' => 'עריכות שלא נמחקו',
  'namespacetotals' => 'חלוקת העריכות לפי מרחבי שמות',
  'monthcounts' => 'חלוקת העריכות לפי חודש',
  'topedited' => 'Top edited articles',
  'executed' => 'Executed in $1 seconds',
  'graphalt' => 'Namespace totals pie chart',
  'viewingsource' => 'Viewing source for $1',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => 'Submitted. Thank You!',
  'nograph' => 'User has not yet opted in. If you want to see graphs, please create <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'translatelink' => 'תרגם',
  'edits' => 'עריכות',
  'file' => 'קובץ',
  'show' => 'הצג',
  'hide' => 'הסתר',
  'selectfile' => 'בחר קובץ להציג:',
  'w' => 'שבועות',
  'd' => 'ימים',
  'h' => 'שעות',
  'm' => 'דקות',
  's' => 'שניות',
); ?>