<?php $_config_vars = array (
  'tool' => 'X!\'s सम्पादन काउण्टर',
  'welcome' => ' X!\'s सम्पादन काउण्टरमा स्वागत छ!',
  'username' => 'प्रयोगकर्ता नाम',
  'nosuchuser' => '$1 उपलब्ध छैन।',
  'mainspace' => 'लेख',
  'generalinfo' => 'प्रयोगकर्ता सामान्य जानकारी',
  'groups' => 'प्रयोगकर्ता समूह',
  'firstedit' => 'प्रथम सम्पादन',
  'unique' => 'विचित्र पृष्ठ सम्पादन',
  'average' => 'प्रत्येक पृष्ठ औसत सम्पादन',
  'total' => 'समूचा सम्पादन (मेटिएका लेखसंगै)',
  'deleted' => 'मेटिएका सम्पादन',
  'live' => 'Live सम्पादन',
  'namespacetotals' => 'समूचा सन्दर्भ',
  'monthcounts' => 'महिना गणक',
  'topedited' => 'Top edited pages',
  'graphalt' => 'Namespace Totals Pie Chart',
  'viewingsource' => 'Viewing source for $1',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => 'Submitted. Thank You!',
  'nograph' => 'User has not yet opted in. If you want to see graphs, please create <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'edits' => 'edits',
  'file' => 'File',
  'show' => 'show',
  'hide' => 'hide',
  'selectfile' => 'Select a file to view:',
  'million' => 'Unbelievable. Absolutely unbelievable. This edit counter was created in December 2008, and in under 1.5 years, has amassed over <span style=\'color:red;\'>1 Million Hits</span>. This is astounding. I thank everyone for their continued support of this tool throughout the years. Without your support, this tool would not be in existence. Let\'s hope for another million! --X! 14 May 2010',
); ?>