<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'View Source',
  'language' => 'Choose a language',
  'tool' => 'X!\'s Edit Counter',
  'submit' => 'Submit',
  'nowiki' => '$1 is not a valid wiki',
  'welcome' => 'Welcome to X!\'s edit counter!',
  'username' => 'Username',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 does not exist.',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mainspace' => 'Article',
  'generalinfo' => 'General user info',
  'groups' => 'User groups',
  'firstedit' => 'First change',
  'unique' => 'Unique pages changed',
  'average' => 'Average changes per page',
  'total' => 'Total changes (including deleted)',
  'deleted' => 'Deleted changes',
  'live' => 'Live changes',
  'namespacetotals' => 'Namespace totals',
  'monthcounts' => 'Month counts',
  'topedited' => 'Most changed articles',
  'executed' => 'Made in $1 seconds',
  'graphalt' => 'Namespace totals pie chart',
  'viewingsource' => 'Showing source for $1',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => 'Submitted. Thank You!',
  'nograph' => 'User has not let people see their graph. If you want to see graphs, please make <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content, or you can make <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'translatelink' => 'translate',
  'edits' => 'changes',
  'file' => 'File',
  'show' => 'show',
  'hide' => 'hide',
  'selectfile' => 'Select a file to see:',
  'w' => 'weeks',
  'd' => 'days',
  'h' => 'hours',
  'm' => 'minutes',
  's' => 'seconds',
  'million' => 'Unbelievable. Absolutely unbelievable. This edit counter was created in December 2008, and in under 1.5 years, has amassed over <span style=\'color:red;\'>1 Million Hits</span>. This is astounding. I thank everyone for their continued support of this tool throughout the years. Without your support, this tool would not be in existence. Let\'s hope for another million! --X! 14 May 2010',
); ?>