<?php $_config_vars = array (
  'title' => 'Tools di X!',
  'source' => 'Visualizza sorgente',
  'language' => 'Scegli una lingua',
  'tool' => 'Edit Counter di X!',
  'submit' => 'Invia',
  'nowiki' => '$1 non è una wiki valida',
  'welcome' => 'Benvenuto nell\'edit counter di X!',
  'username' => 'Nome utente',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Errore MySQL, comunicalo a X! usando <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>il bug reporter.</a> Assicurati di riportate il seguente SQL error quando lo comunichi:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 non esiste.',
  'highreplag' => 'Attenzione: <a href=\'https://wiki.toolserver.org/view/Replag\'>Il lag di risposta</a> è troppo alto, le modifiche posteriori a $1 potrebbero non essere visualizzate.',
  'mainspace' => 'Voce',
  'generalinfo' => 'Informazioni generali sull\'utente',
  'groups' => 'Gruppo utente',
  'firstedit' => 'Primo edit',
  'unique' => 'Numero di articoli editati',
  'average' => 'Media edits per pagina',
  'total' => 'Edits totali (compresi gli edits cancellati)',
  'deleted' => 'Edits cancellati',
  'live' => 'Edits veri e propri',
  'namespacetotals' => 'Totali per namespace',
  'monthcounts' => 'Totale per mese',
  'topedited' => 'Articoli più editati',
  'executed' => 'Eseguito in $1 secondi',
  'graphalt' => 'Grafico a torta diviso per namespace',
  'viewingsource' => 'Visualizzazione sorgente per $1',
  'sourceviewer' => 'Sorgente per l\'Edit Counter di Soxred93',
  'translation' => 'Traduttore per l\'Edit Counter di Soxred93',
  'submitted' => 'Inviato. Grazie!',
  'nograph' => 'Non hai attivato l\'opt in. Se vuoi visualizzare i grafici crea <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>Utente:$1/EditCounterOptIn.js</a> con un contenuto qualsiasi. In alternativa, puoi creare <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> per l\'optin in tutti i progetti wiki.',
  'notopedit' => 'Spiacente, ma per ottimizzare le risorse del toolserver, la voce Articoli più editati è disabilitata per gli utenti con più di 45000 edits.',
  'translatelink' => 'traduci',
  'edits' => 'edits',
  'file' => 'File',
  'show' => 'mostra',
  'hide' => 'nascondi',
  'selectfile' => 'Scegli un file da visualizzare:',
  'w' => 'settimane',
  'd' => 'giorni',
  'h' => 'ore',
  'm' => 'minuti',
  's' => 'secondi',
); ?>