<?php $_config_vars = array (
  'title' => 'X!\'s værktøjer',
  'source' => 'Se Kilde',
  'language' => 'Vælg et sprog',
  'tool' => 'X!\'s Redigeringstæller',
  'submit' => 'Gem',
  'nowiki' => '$1 er ikke en gyldig wiki',
  'welcome' => 'Velkommen til X!\'s redigeringstæller!',
  'username' => 'Brugernavn',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL fejl, rapportér venligst til X! ved at bruge <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>bug rapportøren.</a> Vær sikker på at rapportere følgende  SQL fejl:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 eksisterer ikke.',
  'highreplag' => 'Advarsel: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replikationslag</a> er høj, ændringer nyere end $1 vises muligvis ikke.',
  'mainspace' => 'Artikel',
  'generalinfo' => 'Generel bruger info',
  'groups' => 'Brugergrupper',
  'firstedit' => 'Første redigering',
  'unique' => 'Unikke artikler redigeret',
  'average' => 'Gennemsnitlige redigeringer per side',
  'total' => 'Totale antal redigeringer (inklusive slettede)',
  'deleted' => 'Slettede redigeringer',
  'live' => 'Levende redigeringer',
  'namespacetotals' => 'Navnerum totaler',
  'monthcounts' => 'Månedstal',
  'topedited' => 'Top redigerede artikler',
  'executed' => 'Udført i $1 sekunder',
  'graphalt' => 'Navnerum totaler cirkeldiagram',
  'viewingsource' => 'Ser kilde for $1',
  'sourceviewer' => 'Kilde for X!\'s Redigeringstæller',
  'translation' => 'X!\'s Redigeringstællers Oversætter',
  'submitted' => 'Gemt. Tak!',
  'nograph' => 'Bruger endnu ikke tilmeldt. Om du vil se diagrammer, opret venligst <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> med hvilket som helst indhold. Som alternativ kan du oprette <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> for at tilmelde alle Wikimedias wikier.',
  'notopedit' => 'Desværre, men for at kun forbruge min fair andel af toolservers resurser, er top redigerede artikler slået fra for brugere med mere end 45000 redigeringer.',
  'translatelink' => 'oversæt',
  'edits' => 'redigeringer',
  'file' => 'Fil',
  'show' => 'vis',
  'hide' => 'gem',
  'selectfile' => 'Vælg en fil at se:',
  'w' => 'uger',
  'd' => 'dage',
  'h' => 'timer',
  'm' => 'minutter',
  's' => 'sekunder',
); ?>