<?php $_config_vars = array (
  'title' => 'Għodda ta\' X!',
  'source' => 'Ara s-sors',
  'language' => 'Agħżel lingwa',
  'tool' => 'Kontatur tal-modifiki ta\' X!',
  'submit' => 'Ibgħat',
  'nowiki' => '$1 mhijiex wiki valida',
  'welcome' => 'Merħba fil-kontatur tal-modifiki ta\' X!!',
  'username' => 'Isem tal-utent',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Żball MySQL, jekk jogħġbok irrapporta lil X! billi tuża\' l-<a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>bug reporter</a>. Kun żgur li tirrapporta l-iżball SQL segwenti meta tirrapporta:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 ma jeżistix.',
  'highreplag' => 'Twisija: Il-<a href=\'https://wiki.toolserver.org/view/Replag\'>lag ta\' replikazzjoni</a> huwa għoli, tibdil iġded minn $1 jistsa\' ma jidhirx.',
  'mainspace' => 'Artiklu',
  'generalinfo' => 'Informazzjoni ġenerali fuq l-utent',
  'groups' => 'Gruppi tal-utent',
  'firstedit' => 'L-ewwel modifika',
  'unique' => 'Numru ta\' artikli modifikati',
  'average' => 'Medja ta\' modifiki kull paġna',
  'total' => 'Total ta\' modifiki (jinkludi dawk imħassrin)',
  'deleted' => 'Modifiki mħassra',
  'live' => 'Modifiki veri u proprji',
  'namespacetotals' => 'Total fl-ispazji tal-isem',
  'monthcounts' => 'Għadd fix-xahar',
  'topedited' => 'L-aktar artikli modifikati',
  'executed' => 'Esegwiti f\'$1 sekondi',
  'graphalt' => 'Dijagramma ċirkulari tal-ispazji tal-isem',
  'viewingsource' => 'Qed tara s-sors ta\' $1',
  'sourceviewer' => 'Sors għall-Kontatur tal-modifiki ta\' Soxred93',
  'translation' => 'Traduttur tal-Kontatur tal-modifiki ta\' Soxred93',
  'submitted' => 'Intbagħtet. Grazzi!',
  'nograph' => 'Ma attivajtx l-opt in. Jekk tixtieq tara l-grafi, jekk jogħġbok oħloq <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> b\'kwalunkwe kontenut. Tista\' wkoll toħloq <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> għall-opt-in fil-proġetti wiki kollha tal-Wikimedia.',
  'notopedit' => 'Jiddispjaċini, imma sabiex nottimizza r-riżorsi tat-toolserver, L-Aktar Artikli Modifikati hi diżabilitata għal utenti b\'iktar minn 45,000 modifika.',
  'translatelink' => 'ittraduċi',
  'edits' => 'modifiki',
  'file' => 'Fajl',
  'show' => 'uri',
  'hide' => 'aħbi',
  'selectfile' => 'Agħżel fajl li tixtieq tara:',
  'w' => 'ġimgħat',
  'd' => 'ġranet',
  'h' => 'sigħat',
  'm' => 'minuti',
  's' => 'sekondi',
  'million' => 'Inkredibbli. Tassew inkredibbli. Dan il-kontatur tal-modifiki ġie maħluq f\'Diċembru tal-2008 u f\'temp ta\' sena u nofs, ġabar iktar minn <span style=\'color:red;\'>Miljun Żjara</span>. Din hija ċifra inkredibbli. Nirringrazzja lil kulħadd għas-sosten kontinwu ta\' din l-għodda matul is-snin. Mingħajr is-sosten tagħkom, din l-għodda ma kinitx tkun possibbli. Ejjew nisperaw għal miljun ieħor! --X! 14 ta\' Mejju 2010',
); ?>