<?php $_config_vars = array (
  'tool' => 'Бројач измена корисника X!',
  'welcome' => 'Добродишли на бројач измена корисника X!',
  'username' => 'Корисничко име:',
  'nosuchuser' => '$1 не постоји.',
  'mainspace' => 'Чланак',
  'generalinfo' => 'Опште о кориснику',
  'groups' => 'Корисничка група',
  'firstedit' => 'Прва измена',
  'unique' => 'Мењао различитих страна',
  'average' => 'Просечан број измена по страни',
  'total' => 'Укупан број измена (укључујући избрисане)',
  'deleted' => 'Избрисане измене',
  'live' => 'Измене',
  'namespacetotals' => 'Број измена по именским просторима',
  'monthcounts' => 'Број измена по месецима',
  'topedited' => 'Начешће уређивани чланци',
  'graphalt' => 'График броја измена по именским просторима',
  'viewingsource' => 'Viewing source for $1',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => 'Поднесено. Хвала Вам!',
  'nograph' => 'User has not yet opted in. Ако желите а видите график, молимо направите <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'edits' => 'измене',
  'file' => 'Слика',
  'show' => 'Покажи',
  'hide' => 'Сакриј',
  'selectfile' => 'Одабери слику:',
  'million' => 'Невероватно. Просто невероватно. Овај бројач измена је направљен у децембру 2008, и након мање од 18 месеци је скупио <span style=\'color:red;\'>милион погодака</span>. То је невероватно. Захваљујем се свима на подршци овог бројача током година. Без ваше подршке, овог бројача не би било.Надајмо се још једном милиону! --X! 14. маја 2010.',
); ?>