<?php $_config_vars = array (
  'title' => 'Fitaovan\'i X!',
  'source' => 'Hijery fango',
  'language' => 'Hisafidy fiteny',
  'tool' => 'Mpanisa fanovan\'i X!',
  'submit' => 'Alefa',
  'nowiki' => 'Tsy wiki ny $1',
  'welcome' => 'Tonga soa eto amin\'ny mpanisa fanovan\'i X!',
  'username' => 'Anaram-pikambana',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Tsi-fetezana MySQL, torio any amin\'i X! amin\'ny alàlan\'ny fampiasana  <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>ny mpitory bug.</a> Marino tsara raha tena ilay tsi-fetezana SQL  :<br /><pre>$1</pre>',
  'nosuchuser' => 'Tsy nahitana $1',
  'highreplag' => 'Tandremo: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mainspace' => 'Lahatsoratra',
  'generalinfo' => 'Fampahalalana amin\'ny ankapoben\'ny mpikambana',
  'groups' => 'Vondrom-pikambana',
  'firstedit' => 'Fanovana voalohany',
  'unique' => 'Lahatsoratra samihafa efa novaina',
  'average' => 'Elanelan\'ny fanovana isaky ny pejy',
  'total' => 'Isa tontalin\'ny fanovana (miaraka amin\'ny voafafa)',
  'deleted' => 'Fanovana voafafa',
  'live' => 'Fanovana tsy voafafa',
  'namespacetotals' => 'Tontalin’ny anaran-tsehatra',
  'monthcounts' => 'Isam-bolana',
  'topedited' => 'Ny sehatra tena voaova indrindra',
  'executed' => 'Voaomana tao anatin\'ny $1 segondra',
  'graphalt' => 'Fizarana ny fanovana araka ny anaran-tsehatra',
  'viewingsource' => 'Hijery fango ho an\'i $1',
  'sourceviewer' => 'Fangon\'ny mpanisa fanovan\'i Soxred93',
  'translation' => 'Mpandika tenin\'ny mpanisa fanovan\'i Soxred93',
  'submitted' => 'Lasa. Misaotra betsaka!',
  'nograph' => 'Tsy nisoratra tamin\'io ity mpikambana ity. raha tianao jerena ny sary, amboary <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a>. Asio ao izay tianao ho asiana. Azonao foronina <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Azafady, fa mba tsy haka ny loharano rehetra an\'i Toolserver, tsy alefa ny fizarana momban\'ny lahatsoratra voaova indrindra ho an\'ny mpikambana miisa fanovana mahery ny 45 000',
  'translatelink' => 'handika',
  'edits' => 'fanovana',
  'file' => 'Rakitra',
  'show' => 'aseho',
  'hide' => 'asitriho',
  'selectfile' => 'Misafidia rakitra hojerena',
  'w' => 'herinandro',
  'd' => 'andro',
  'h' => 'ora',
  'm' => 'minitra',
  's' => 'segondra',
); ?>