<?php $_config_vars = array (
  'title' => 'X!\'i tööriistad',
  'source' => 'Vaata lähtekoodi',
  'language' => 'Vali keel',
  'tool' => 'X!\'i Edit Counter',
  'submit' => 'Esita',
  'nowiki' => '$1 nimelist vikit ei eksisteeri',
  'welcome' => 'Welcome to X!\'s edit counter!',
  'username' => 'Kasutajanimi',
  'wiki' => 'Viki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 nimelist kasutajat ei eksisteeri',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mainspace' => 'Artikkel',
  'generalinfo' => 'Kasutaja andmed',
  'groups' => 'Kuulub rühmadesse',
  'firstedit' => 'Esimene redaktsioon',
  'unique' => 'Redigeerinud erinevaid artikleid',
  'average' => 'Keskmiselt redigeerimisi lehe kohta',
  'total' => 'Redaktsioone kokku (kaasaarvatud kustutatud)',
  'deleted' => 'Kustutatud redaktsioone',
  'live' => 'Kehtivaid redaktsioone',
  'namespacetotals' => 'Redaktsioone nimeruumis',
  'monthcounts' => 'Kuude kaupa',
  'topedited' => 'Enim redigeeritud artiklid',
  'executed' => 'Genereeritud $1 sekundiga',
  'graphalt' => 'Nimeruumi koguandmete graafik',
  'viewingsource' => 'Vaata $1 lähtefaili',
  'sourceviewer' => 'Lähtekood Soxred93\'s Edit Counter\'i jaoks',
  'translation' => 'Soxred93\'s Edit Counter\'i tõlkija',
  'submitted' => 'Esitatud. Tänan!',
  'nograph' => 'User has not yet opted in. If you want to see graphs, please create <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'translatelink' => 'Tõlgi',
  'edits' => 'Redaktsiooni',
  'file' => 'File',
  'show' => 'näita',
  'hide' => 'peida',
  'selectfile' => 'Vali fail vaatamiseks:',
  'w' => 'nädalad',
  'd' => 'päevad',
  'h' => 'tunnid',
  'm' => 'minutid',
  's' => 'sekundit',
); ?>