<?php $_config_vars = array (
  'title' => 'Ferramentas de X!',
  'source' => 'Ver código fonte',
  'language' => 'Selecciona unha linguaxe',
  'tool' => 'Contador de Edicións de X!',
  'submit' => 'Enviar',
  'nowiki' => '$1 non é unha wiki válida',
  'welcome' => 'Benvido ao contador de edicións de X!',
  'username' => 'Nome de usuario',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 non existe.',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mainspace' => 'Artigo',
  'generalinfo' => 'Información xeral do usuario',
  'groups' => 'Grupos do usuario',
  'firstedit' => 'Primeira edición',
  'unique' => 'Artigos únicos editados',
  'average' => 'Media de edicións por páxina',
  'total' => 'Total de edicións (incluíndo as eliminadas)',
  'deleted' => 'Edicións eliminadas',
  'live' => 'Live edits',
  'namespacetotals' => 'Totais por espazos de nomes',
  'monthcounts' => 'Contador por meses',
  'topedited' => 'Artigos máis editados',
  'executed' => 'Executado en $1 segundos',
  'graphalt' => 'Gráfico de totais por nomes de espazos',
  'viewingsource' => 'Vendo código fonte de $1',
  'sourceviewer' => 'Ver código fonte do Contador de Edicións de Soxred93',
  'translation' => 'Traductor do Contador de Edicións de Soxred93',
  'submitted' => 'Enviado. Grazas!',
  'nograph' => 'User has not yet opted in. If you want to see graphs, please create <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'translatelink' => 'traducir',
  'edits' => 'edicións',
  'file' => 'Ficheiro',
  'show' => 'amosar',
  'hide' => 'agochar',
  'selectfile' => 'Select a file to view:',
  'w' => 'semanas',
  'd' => 'días',
  'h' => 'horas',
  'm' => 'minutos',
  's' => 'segundos',
); ?>