<?php $_config_vars = array (
  'title' => 'X!s verktøy',
  'source' => 'Vis kilde',
  'language' => 'Velg språk',
  'tool' => 'X!s redigeringsteller',
  'submit' => 'Gå',
  'nowiki' => '$1 er ikke en gyldig wiki',
  'welcome' => 'Velkommen til X!s redigeringsteller',
  'username' => 'Brukernavn',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL-feil, vennligst rapporter den til X! ved å bruke <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>feilrapporteringa</a>. Husk å ta med følgende feilmelding i rapporten:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 finnes ikke.',
  'highreplag' => 'Obs: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replikasjonstida</a> er høy, endringer som er nyere enn $1 vil ikke vises.',
  'mainspace' => 'Artikkel',
  'generalinfo' => 'Generell brukerinformasjon',
  'groups' => 'Brukergrupper',
  'firstedit' => 'Første redigering',
  'unique' => 'Unike redigerte sider',
  'average' => 'Redigeringer pr. side',
  'total' => 'Totalt antall redigeringer (inkludert slettede)',
  'deleted' => 'Slettede redigeringer',
  'live' => 'Ikke-slettede redigeringer',
  'namespacetotals' => 'Navnerom',
  'monthcounts' => 'Månedlige redigeringer',
  'topedited' => 'Mest redigerte artikler',
  'executed' => 'Utført på $1 sekunder',
  'graphalt' => 'Paidiagram over navnerom',
  'viewingsource' => 'Viser kilde for $1',
  'sourceviewer' => 'Kilde for Soxred93s redigeringsteller',
  'translation' => 'Soxred93s redigeringstelleroversetting',
  'submitted' => 'Levert. Takk!',
  'nograph' => 'Brukeren har ikke godkjent dette ennå. Hvis du vil se grafer, opprett <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> med et eller annet innhold. Du kan eventuelt opprette <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> for å aktivere på alle Wikimedia-wikier.',
  'notopedit' => 'Beklager, men for å ikke bruke for mye ressurser av toolserveren kan ikke de mest redigerte artiklene vises for brukere med mer enn 45 000 redigeringer.',
  'translatelink' => 'oversett',
  'edits' => 'redigeringer',
  'file' => 'Fil',
  'show' => 'vis',
  'hide' => 'skjul',
  'selectfile' => 'Velg fil å vise',
  'w' => 'uker',
  'd' => 'dager',
  'h' => 'timer',
  'm' => 'minutter',
  's' => 'sekunder',
  'million' => 'Utrolig. Denne redigeringstelleren har fått over én million treff siden den ble oppretta i desember 2008. Jeg vil takke alle for støtten jeg har fått opp gjennom åra. Uten deres støtte hadde det ikke vært mulig. La oss håpe på at det blir enda en million! --X! 14. mai 2010',
); ?>