<?php $_config_vars = array (
  'tool' => 'ئامێر',
  'welcome' => 'بەخێرھاتی',
  'username' => 'ناوی بەکارھێنەری',
  'nosuchuser' => '$1 does not exist.',
  'mainspace' => 'وتار',
  'generalinfo' => 'General user info',
  'groups' => 'User groups',
  'firstedit' => 'یەکەمین دەستکاری',
  'unique' => 'Unique pages edited',
  'average' => 'Average edits per page',
  'total' => 'Total edits (including deleted)',
  'deleted' => 'دەستکارییە سڕاوەکان',
  'live' => 'دەستکارییە زیندووەکان',
  'namespacetotals' => 'Namespace Totals',
  'monthcounts' => 'Month counts',
  'topedited' => 'Top edited pages',
  'graphalt' => 'Namespace Totals Pie Chart',
  'viewingsource' => 'Viewing source for $1',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => 'سوپاس. نێردرا!',
  'nograph' => 'User has not yet opted in. If you want to see graphs, please create <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'edits' => 'edits',
  'file' => 'پەڕگە',
  'show' => 'نیشاندان',
  'hide' => 'شاردنەوە',
  'selectfile' => 'پەڕگەیەک بۆ نیشاندان ھەڵبژێرە:',
  'million' => 'Unbelievable. Absolutely unbelievable. This edit counter was created in December 2008, and in under 1.5 years, has amassed over <span style=\'color:red;\'>1 Million Hits</span>. This is astounding. I thank everyone for their continued support of this tool throughout the years. Without your support, this tool would not be in existence. Let\'s hope for another million! --X! 14 May 2010',
); ?>