<?php $_config_vars = array (
  'title' => 'X! eszközök',
  'source' => 'Forrás megtekintése',
  'language' => 'Válassz nyelvet',
  'tool' => 'X!\'s Edit Counter',
  'submit' => 'Mehet',
  'nowiki' => '$1 is not a valid wiki',
  'welcome' => 'Welcome to X!\'s edit counter!',
  'username' => 'Felhasználónév',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL hiba, jelentsd az X! felé  <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>Hiba beküldő.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 nem létezik',
  'highreplag' => 'Figyelmeztetés: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mainspace' => 'Cikk',
  'generalinfo' => 'Általnos Felhasználói infó',
  'groups' => 'Felhasználói csoportok',
  'firstedit' => 'Első szerkesztés',
  'unique' => 'Egyedi szerkesztett cikkek',
  'average' => 'Átlagos oldalankénti szerkesztés',
  'total' => 'Összes szerkesztés (töröltekkel együtt)',
  'deleted' => 'Törölt szerkesztések',
  'live' => 'Folyamatban lévő szerkesztések',
  'namespacetotals' => 'Névterek összesen',
  'monthcounts' => 'Hónapok száma',
  'topedited' => 'Legtöbbet szerkesztett cikkek',
  'executed' => 'Futási idő $1 másodperc',
  'graphalt' => 'Névterek összesen pie lista',
  'viewingsource' => 'A forrást megtekinti $1',
  'sourceviewer' => 'Forrás Soxred93 számlálójának szerkesztés',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => 'Beküldve. Köszönjük!',
  'nograph' => 'User has not yet opted in. If you want to see graphs, please create <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sajnálom, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'translatelink' => 'fordítás',
  'edits' => 'szerkesztés',
  'file' => 'Fájl',
  'show' => 'megtekint',
  'hide' => 'elrejt',
  'selectfile' => 'Válasszon fájlt a megtekintéshez:',
  'w' => 'hét',
  'd' => 'nap',
  'h' => 'óra',
  'm' => 'perc',
  's' => 'másodperc',
); ?>