<?php $_config_vars = array (
  'tool' => 'X!\'s Contador de ediciones',
  'welcome' => '¡Bienvenido a X!\'s contador de ediciones!',
  'username' => 'Nombre de usuario',
  'nosuchuser' => '$1 no existe',
  'mainspace' => 'Artículo',
  'generalinfo' => 'Información general del usuario',
  'groups' => 'Grupos de usuarios',
  'firstedit' => 'Primera edición',
  'unique' => 'Únicos artículos editados',
  'average' => 'Promedio de ediciones por página',
  'total' => 'Total de ediciones (incluyendo borradas)',
  'deleted' => 'Ediciones borradas',
  'live' => 'Ediciones en vivo',
  'namespacetotals' => 'Espacio de nombres totales',
  'monthcounts' => 'Ediciones mes a mes',
  'topedited' => 'Los artículos más editados',
  'graphalt' => 'Espacio de nombres totales en el gráfico circular',
  'viewingsource' => 'Viendo la fuente por $1',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Soxred93  Traductor del Contador de Ediciones',
  'submitted' => 'Enviado. ¡Gracias!',
  'nograph' => 'El usuario no ha optado. Si usted desea ver los gráficos, por favor crea <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> con cualquier contenido. Como alternativa, puede crear <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> para opt-in en todas las Wikimedia wikis.',
  'notopedit' => 'Lo sentimos, pero para consumir mi parte justa de los recursos del toolserver, El top de artículos editados están deshabilitados para usuarios con más de 45000 ediciones.',
  'edits' => 'ediciones',
  'file' => 'Carpeta',
  'show' => 'mostrar',
  'hide' => 'ocultar',
  'selectfile' => 'Selecciona una carpeta para verla:',
  'million' => 'Unbelievable. Absolutely unbelievable. This edit counter was created in December 2008, and in under 1.5 years, has amassed over <span style=\'color:red;\'>1 Million Hits</span>. This is astounding. I thank everyone for their continued support of this tool throughout the years. Without your support, this tool would not be in existence. Let\'s hope for another million! --X! 14 May 2010',
); ?>