<?php $_config_vars = array (
  'title' => 'Eines X!',
  'source' => 'Veure el font',
  'language' => 'Selecciona una llengua',
  'tool' => 'Comptador d\'edicions X!',
  'submit' => 'Envia',
  'nowiki' => '$1 no és una wiki vàlida',
  'welcome' => 'Benvinguts al comptador d\'edicions X!',
  'username' => 'Usuari',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 no existeix',
  'highreplag' => 'Atenció: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mainspace' => 'Article',
  'generalinfo' => 'Informació general de l\'usuari',
  'groups' => 'User groups',
  'firstedit' => 'Primera edició',
  'unique' => 'Unique articles edited',
  'average' => 'Mitjana d\'edicions per pàgina',
  'total' => 'Edicions totals (incloent-hi les eliminades)',
  'deleted' => 'Edicions eliminades',
  'live' => 'Edicions vigents',
  'namespacetotals' => 'Namespace totals',
  'monthcounts' => 'Comptador mensual',
  'topedited' => 'Articles amb més edicions',
  'executed' => 'Executed in $1 seconds',
  'graphalt' => 'Namespace totals pie chart',
  'viewingsource' => 'Viewing source for $1',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Traductor del comptador d\'edicions de Soxred93',
  'submitted' => 'Enviat. Gràcies!',
  'nograph' => 'User has not yet opted in. If you want to see graphs, please create <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'translatelink' => 'tradueix',
  'edits' => 'edicions',
  'file' => 'Fitxer',
  'show' => 'mostra',
  'hide' => 'amaga',
  'selectfile' => 'Selecciona un fitxer a veure:',
  'w' => 'setmanes',
  'd' => 'dies',
  'h' => 'hores',
  'm' => 'minuts',
  's' => 'segons',
); ?>