<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'Kaynağı göster',
  'language' => 'Dil seçiniz',
  'tool' => 'X!\'s Edit Counter',
  'submit' => '',
  'nowiki' => '$1 geçersiz değişken',
  'welcome' => 'X!\'s kullanıcı sayacına hoşgeldiniz',
  'username' => 'Kullanıcı adı',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'nosuchuser' => '$1 does not exist.',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mainspace' => 'Madde',
  'generalinfo' => 'General user info',
  'groups' => 'Kullanıcı grupları',
  'firstedit' => 'İlk değişiklik',
  'unique' => 'Unique articles edited',
  'average' => 'Average edits per page',
  'total' => 'Toplam değişiklik (silinenler dahil)',
  'deleted' => 'Silinen değişiklikler',
  'live' => 'Live edits',
  'namespacetotals' => 'Namespace totals',
  'monthcounts' => 'Aylık sayaç',
  'topedited' => 'Top edited articles',
  'executed' => 'Executed in $1 seconds',
  'graphalt' => 'Namespace totals pie chart',
  'viewingsource' => 'Viewing source for $1',
  'sourceviewer' => 'Source for Soxred93\'s Edit Counter',
  'translation' => 'Soxred93\'s Edit Counter Translator',
  'submitted' => 'Submitted. Thank You!',
  'nograph' => 'User has not yet opted in. If you want to see graphs, please create <a href=\'//$2/wiki/User:$1/EditCounterOptIn.js\'>User:$1/EditCounterOptIn.js</a> with any content. Alternatively, you can create <a href=\'//meta.wikimedia.org/wiki/User:$1/EditCounterGlobalOptIn.js\'>meta:User:$1/EditCounterGlobalOptIn.js</a> to opt-in across all Wikimedia wikis.',
  'notopedit' => 'Sorry, but in order to consume my fair share of toolserver resources, Top Edited Articles are disabled for users with over 45000 edits.',
  'translatelink' => 'Çeviri',
  'edits' => 'Değişiklikler',
  'file' => 'Dosya',
  'show' => 'Göster',
  'hide' => 'Gizle',
  'selectfile' => 'Select a file to view:',
  'w' => 'Hafta',
  'd' => 'Gün',
  'h' => 'Saat',
  'm' => 'Dakika',
  's' => 'Saniye',
); ?>