<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'View Source',
  'language' => 'Select a language',
  'executed' => 'Executed in $1 second(s).',
  'tool' => 'Article Blamer',
  'header' => 'Find addition of text in a page history',
  'article' => 'Article',
  'submit' => 'Submit',
  'nowiki' => '$1 is not a valid wiki',
  'welcome' => 'Welcome to X!\'s edit counter!',
  'wiki' => 'Wiki',
  'tosearch' => 'Text to search for',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'nosuchpage' => '$1 does not exist.',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'w' => 'weeks',
  'd' => 'days',
  'h' => 'hours',
  'm' => 'minutes',
  's' => 'seconds',
  'nofollowredir' => 'Don\'t follow redirects',
  'added' => 'Revisions that added specified text: ',
  'diff' => 'diff',
  'hist' => 'hist',
  'talk' => 'talk',
); ?>