<?php $_config_vars = array (
  'title' => 'X!\'s værktøjer',
  'source' => 'Kildekode',
  'language' => 'Vælg et sprog',
  'executed' => 'Udført på $1 sekunder',
  'memory' => 'Bruger $1 megabyte hukommelse at udføre',
  'submit' => 'Gem',
  'nowiki' => '$1 er ikke en gyldig wiki',
  'bugs' => 'Fejl',
  'mysqlerror' => 'MySQL fejl, rapportér venligst til X! ved at bruge <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>bug rapportøren.</a> Vær sikker på at rapportere følgende  SQL fejl:<br /><pre>$1</pre>',
  'highreplag' => 'Advarsel: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Replikationslag</a> er høj, ændringer nyere end $1 vises muligvis ikke.',
  'mo' => 'måneder',
  'w' => 'uger',
  'd' => 'dage',
  'h' => 'timer',
  'm' => 'minutter',
  's' => 'sekunder',
  'decimal_separator' => ',',
  'thousands_separator' => '.',
  'wiki' => 'Wiki',
  'translatelink' => 'oversæt',
); ?>