<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'View Source',
  'language' => 'Select a language',
  'executed' => 'Executed in $1 second(s).',
  'memory' => 'Taken $1 megabytes of memory to execute.',
  'submit' => 'Submit',
  'nowiki' => '$1 is not a valid wiki',
  'bugs' => 'Bugs',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Caution: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mo' => 'months',
  'w' => 'weeks',
  'd' => 'days',
  'h' => 'hours',
  'm' => 'minutes',
  's' => 'seconds',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'Wiki',
  'translatelink' => 'Translate',
  'noexist' => '$1 does not exist',
  'twitter' => 'Follow on <a href=\'//twitter.com/soxred93tools\'>Twitter!</a>',
); ?>