<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'Vidi izvor',
  'language' => 'Izaberi jezik',
  'submit' => 'Pošalji',
  'nowiki' => '$1 nije ispravna wiki',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL pogreška, molim izvjestite X! koristeći <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>the bug reporter.</a> Provjerite da li ste unijeli slijedeću SQL pogrešku pri izvješću:<br /><pre>$1</pre>',
  'highreplag' => 'Upozorenje: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Kašnjenje odgovora</a> je veliko, promjene novije od $1 možda neće biti prikazane.',
  'executed' => 'Izvršeno u $1 sekundi',
  'translatelink' => 'prevedi',
  'w' => 'tjedana',
  'd' => 'dana',
  'h' => 'sati',
  'm' => 'minuta',
  's' => 'sekundi',
); ?>