<?php $_config_vars = array (
  'title' => 'X!’র সরঞ্জাম',
  'source' => 'সোর্স দেখুন',
  'language' => 'ভাষা নির্বাচন করুন',
  'executed' => 'সম্পাদনা সংখ্যা জানতে সময় লেগেছে $1 সেকেন্ড',
  'memory' => 'এক্সিকিউট করতে $1 মেগাবাইট মেমোরি খরচ হয়েছে',
  'submit' => 'সংরক্ষণ',
  'nowiki' => '$1 কোনো প্রযোজ্য উইকি নয়',
  'bugs' => 'বাগ',
  'mysqlerror' => 'মাইএসকিউএল ত্রুটি, <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>বাগ রিপোর্টার</a> ব্যবহার করে X!-কে ব্যাপারটি অবগত করুন। নিচের এসকিউএল ত্রুটিটি জানানোর ক্ষেত্রে নিশ্চিত হোন যে:<br /><pre>$1</pre>',
  'highreplag' => 'সাবধান: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>রেপ্লিকেশন ল্যাগের</a> মাত্রা অনেক বেশি, $1-এর চেয়ে নতুন পরিবর্তনগুলো প্রদর্শিত নাও হতে পারে।',
  'mo' => 'মাস',
  'w' => 'সপ্তাহ',
  'd' => 'দিন',
  'h' => 'ঘন্টা',
  'm' => 'মিনিট',
  's' => 'সেকেন্ড',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'উইকি',
  'translatelink' => 'অনুবাদ',
  'noexist' => '$1 প্রযোজ্য নয়',
); ?>