<?php $_config_vars = array (
  'title' => 'La herramienta de X!',
  'source' => 'Ver código fuente',
  'language' => 'Selecciona un idioma',
  'executed' => 'Ejecutado en  $1 segundos',
  'memory' => 'Utilizó $1 megabytes de memoria para ejecutar.',
  'submit' => 'Enviar',
  'nowiki' => '$1 esta Wiki no es válida',
  'bugs' => 'Bugs',
  'mysqlerror' => 'Error de MySQL, por favor informe al X! usando <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>el informe de fallos.</a> Asegúrese de reportar el error:<br /><pre>$1</pre>',
  'highreplag' => 'Precaución: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Replicación de retraso</a> es alta, los cambios más recientes que $ 1 no puede ser mostrada.',
  'mo' => 'meses',
  'w' => 'semanas',
  'd' => 'dias',
  'h' => 'horas',
  'm' => 'minutos',
  's' => 'segundos',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'Wiki',
  'translatelink' => 'traducir',
  'noexist' => '$1 no existe',
); ?>