<?php $_config_vars = array (
  'title' => 'X!s verktøy',
  'source' => 'Vis kilde',
  'language' => 'Velg språk',
  'submit' => 'Gå',
  'nowiki' => '$1 er ikke en gyldig wiki',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL-feil, vennligst rapporter den til X! ved å bruke <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>feilrapporteringa</a>. Husk å ta med følgende feilmelding i rapporten:<br /><pre>$1</pre>',
  'highreplag' => 'Obs: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Replikasjonstida</a> er høy, endringer som er nyere enn $1 vil ikke vises.',
  'executed' => 'Utført på $1 sekunder',
  'translatelink' => 'oversett',
  'w' => 'uker',
  'd' => 'dager',
  'h' => 'timer',
  'm' => 'minutter',
  's' => 'sekunder',
); ?>