<?php $_config_vars = array (
  'title' => 'X!:s verktyg',
  'source' => 'Visa källa',
  'language' => 'Välj språk',
  'executed' => 'Körd på $1 sekunder.',
  'memory' => 'Tog $1 megabyte minne att utföra.',
  'submit' => 'Skicka',
  'nowiki' => '$1 är inte en giltig wiki',
  'bugs' => 'Buggar',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Varning: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Replication lag</a> är hög, förändringar som är nyare än $1 kanske inte visas.',
  'mo' => 'months',
  'w' => 'veckor',
  'd' => 'dagar',
  'h' => 'timmar',
  'm' => 'minuter',
  's' => 'sekunder',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'Wiki',
  'translatelink' => 'översätt',
); ?>