<?php $_config_vars = array (
  'title' => 'X!\'s værktøjer',
  'source' => 'Kildekode',
  'language' => 'Vælg et sprog',
  'executed' => 'Udført på $1 sekunder',
  'memory' => 'Bruger $1 megabyte hukommelse at udføre',
  'submit' => 'Gem',
  'nowiki' => '$1 er ikke en gyldig wiki',
  'bugs' => 'Fejl',
  'mysqlerror' => 'MySQL fejl, rapportér venligst til X! ved at bruge <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>bug rapportøren.</a> Vær sikker på at rapportere følgende  SQL fejl:<br /><pre>$1</pre>',
  'highreplag' => 'Advarsel: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replikationslag</a> er høj, ændringer nyere end $1 vises muligvis ikke.',
  'mo' => 'måneder',
  'w' => 'uger',
  'd' => 'dage',
  'h' => 'timer',
  'm' => 'minutter',
  's' => 'sekunder',
  'decimal_separator' => ',',
  'thousands_separator' => '.',
  'wiki' => 'Wiki',
  'translatelink' => 'oversæt',
); ?>