<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'Bekijk code',
  'language' => 'Selecteer een taal',
  'executed' => 'Uitgevoerd in $1 seconden',
  'memory' => 'Taken $1 megabytes of memory to execute.',
  'submit' => 'Verstuur',
  'nowiki' => '$1 is geen toegestane wiki',
  'bugs' => 'Bugs',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs?uselang=nl\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mo' => 'months',
  'w' => 'weken',
  'd' => 'dagen',
  'h' => 'uren',
  'm' => 'minuten',
  's' => 'seconden',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'Wiki',
  'translatelink' => 'Vertaal',
  'noexist' => '$1 does not exist',
); ?>