<?php $_config_vars = array (
  'title' => 'X!:n työkalut',
  'source' => 'Näytä lähdekoodi',
  'language' => 'Valitse kieli',
  'submit' => 'Lähetä',
  'nowiki' => '$1 ei ole kelvollinen wiki',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL-virhe. Ilmoita virheestä käyttäjälle X! seuraavalla <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>ohjelmistovirhesivulla.</a> Varmista, että tämä SQL-virhe on ilmoituksessa:<br /><pre>$1</pre>',
  'highreplag' => 'Varoitus: <a href=\'https://wiki.toolserver.org/view/Replag\'>Päivitysviive</a> on korkea. Muutokset, jotka ovat uudempia kuin $1 eivät välttämättä näy.',
  'executed' => 'Suoritettu $1 sekunnissa',
  'translatelink' => 'käännä',
  'w' => 'viikkoa',
  'd' => 'päivää',
  'h' => 'tuntia',
  'm' => 'minuuttia',
  's' => 'sekuntia',
); ?>