<?php $_config_vars = array (
  'title' => 'Các công cụ của X!',
  'source' => 'Xem mã nguồn',
  'language' => 'Chọn một ngôn ngữ',
  'executed' => 'Quá trình mất $1 giây',
  'memory' => 'Mất $1 megabyte của bộ nhớ để thực hiện.',
  'submit' => 'Gửi',
  'nowiki' => '$1 không phải là wiki hợp lệ',
  'bugs' => 'Lỗi',
  'mysqlerror' => 'Lỗi MySQL, hãy gửi báo cáo đến X! sử dụng <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>mẫu báo lỗi.</a> Hãy chắc chắn bạn đang báo cáo lỗi SQL sau:<br /><pre>$1</pre>',
  'highreplag' => 'Cảnh báo: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> cao, những thay đổi mới hơn $1 có thể sẽ không được hiển thị.',
  'mo' => 'months',
  'w' => 'tuần',
  'd' => 'ngày',
  'h' => 'giờ',
  'm' => 'phút',
  's' => 'giây',
  'decimal_separator' => ',',
  'thousands_separator' => '.',
  'wiki' => 'Wiki',
  'translatelink' => 'dịch',
  'noexist' => '$1 không tồn tại',
); ?>