<?php $_config_vars = array (
  'title' => 'Għodda ta\' X!',
  'source' => 'Ara s-sors',
  'language' => 'Agħżel lingwa',
  'submit' => 'Ibgħat',
  'nowiki' => '$1 mhijiex wiki valida',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Żball MySQL, jekk jogħġbok irrapporta lil X! billi tuża\' l-<a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>bug reporter</a>. Kun żgur li tirrapporta l-iżball SQL segwenti meta tirrapporta:<br /><pre>$1</pre>',
  'highreplag' => 'Twisija: Il-<a href=\'https://wiki.toolserver.org/view/Replag\'>lag ta\' replikazzjoni</a> huwa għoli, tibdil iġded minn $1 jistsa\' ma jidhirx.',
  'executed' => 'Esegwiti f\'$1 sekondi',
  'translatelink' => 'ittraduċi',
  'w' => 'ġimgħat',
  'd' => 'ġranet',
  'h' => 'sigħat',
  'm' => 'minuti',
  's' => 'sekondi',
); ?>