<?php $_config_vars = array (
  'title' => 'Strumenti di X!',
  'source' => 'Visualizza sorgente',
  'language' => 'Scegli una lingua',
  'executed' => 'Eseguito in $1 secondi',
  'memory' => 'Utilizzati $1 megabyte di memoria per eseguire.',
  'submit' => 'Invia',
  'nowiki' => '$1 non è una wiki valida',
  'bugs' => 'Bug',
  'mysqlerror' => 'Errore MySQL, comunicalo a X! usando <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>il bug reporter.</a> Assicurati di riportate il seguente SQL error quando lo comunichi:<br /><pre>$1</pre>',
  'highreplag' => 'Attenzione: <a href=\'https://wiki.toolserver.org/view/Replag\'>Il lag di risposta</a> è troppo alto, le modifiche posteriori a $1 potrebbero non essere visualizzate.',
  'mo' => 'mesi',
  'w' => 'settimane',
  'd' => 'giorni',
  'h' => 'ore',
  'm' => 'minuti',
  's' => 'secondi',
  'decimal_separator' => ',',
  'thousands_separator' => '.',
  'wiki' => 'Wiki',
  'translatelink' => 'traduci',
  'noexist' => '$1 non esiste',
); ?>