<?php $_config_vars = array (
  'title' => 'X!\'i tööriistad',
  'source' => 'Vaata lähtekoodi',
  'language' => 'Vali keel',
  'executed' => 'Genereeritud $1 sekundiga',
  'memory' => 'Taken $1 megabytes of memory to execute.',
  'submit' => 'Esita',
  'nowiki' => '$1 nimelist vikit ei eksisteeri',
  'bugs' => 'Bugs',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mo' => 'kuud',
  'w' => 'nädalat',
  'd' => 'päeva',
  'h' => 'tundi',
  'm' => 'minutit',
  's' => 'sekundit',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'Viki',
  'translatelink' => 'Tõlgi',
); ?>