<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'Види код',
  'language' => 'Српски',
  'submit' => 'Поднеси',
  'nowiki' => '$1 није валидна вики',
  'wiki' => 'Вики',
  'mysqlerror' => 'MySQL грешка, молимо пријавите кориснику X! користећи <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>ово.</a> Потрудите се да пријавите следећу SQL грешку:<br /><pre>$1</pre>',
  'highreplag' => 'Пажња: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> је висок, промене новије од $1 можда неће бити приказане.',
  'executed' => 'Извршено за $1 секунди',
  'translatelink' => 'преведи',
  'w' => 'недеља',
  'd' => 'дана',
  'h' => 'сати',
  'm' => 'минута',
  's' => 'секунди',
); ?>