<?php $_config_vars = array (
  'title' => 'Eines X!',
  'source' => 'Veure el font',
  'language' => 'Selecciona una llengua',
  'submit' => 'Envia',
  'nowiki' => '$1 no és una wiki vàlida',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Atenció: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'executed' => 'Executed in $1 seconds',
  'translatelink' => 'tradueix',
  'w' => 'setmanes',
  'd' => 'dies',
  'h' => 'hores',
  'm' => 'minuts',
  's' => 'segons',
); ?>