<?php $_config_vars = array (
  'title' => 'Fitaovan\'i X!',
  'source' => 'Hijery fango',
  'language' => 'Hisafidy fiteny',
  'submit' => 'Alefa',
  'nowiki' => 'Tsy wiki ny $1',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Tsi-fetezana MySQL, torio any amin\'i X! amin\'ny alàlan\'ny fampiasana  <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>ny mpitory bug.</a> Marino tsara raha tena ilay tsi-fetezana SQL  :<br /><pre>$1</pre>',
  'highreplag' => 'Tandremo: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'executed' => 'Voaomana tao anatin\'ny $1 segondra',
  'translatelink' => 'handika',
  'w' => 'herinandro',
  'd' => 'andro',
  'h' => 'ora',
  'm' => 'minitra',
  's' => 'segondra',
); ?>