<?php $_config_vars = array (
  'title' => 'Wärchzyyg vum X!',
  'source' => 'Quälle aaluege',
  'language' => 'E Sproch uuswehle',
  'executed' => 'Uusgfiert in $1 Sekunde',
  'memory' => 'Taken $1 megabytes of memory to execute.',
  'submit' => 'Ibertrage',
  'nowiki' => '$1 isch kei giltig Wiki',
  'bugs' => 'Bugs',
  'mysqlerror' => 'MySQL-Fähler, bitte mäld des an dr X! iber <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>dr Bug-Reporter.</a> Stell sicher, ass Du bi dr Mäldig au dää SQL-Fähler mäldsch:<br /><pre>$1</pre>',
  'highreplag' => 'Grund: <a href=\'https://wiki.toolserver.org/view/Replag\'> Ruckstau </a> isch hoch, s cha syy, ass Änderige, wu nejer sin wie $1, nit aazeigt wäre.',
  'mo' => 'months',
  'w' => 'wuche',
  'd' => 'däg',
  'h' => 'stunde',
  'm' => 'minute',
  's' => 'sekunde',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'Wiki',
  'translatelink' => 'ibersetze',
); ?>