<?php $_config_vars = array (
  'title' => 'X!的工具',
  'source' => '檢視原始碼',
  'language' => '選擇一種語言',
  'submit' => '提交',
  'nowiki' => '$1不是合法的wiki',
  'wiki' => '維基',
  'mysqlerror' => 'MySQL错误，请向X!<a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>报告错误</a>。请在您的报告中附带下列SQL错误信息：<br /><pre>$1</pre>',
  'highreplag' => '警告：<a href=\'https://wiki.toolserver.org/view/Replag\'>复制延迟</a>过高，$1以后的修订可能无法显示。',
  'executed' => '用時 $1 秒',
  'translatelink' => '翻譯',
  'w' => '週',
  'd' => '日',
  'h' => '小時',
  'm' => '分鐘',
  's' => '秒',
); ?>