<?php $_config_vars = array (
  'title' => 'X! erabiltzailearen tresnak',
  'source' => 'Ikusi iturburua',
  'language' => 'Hautatu hizkuntza',
  'submit' => 'Igorri',
  'nowiki' => '$1 ez da baliozko wikia',
  'wiki' => 'Wikia',
  'mysqlerror' => 'MySQL errorea. Mesedez, bidali horren berri X! erabiltzaileari, <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>akatsak jakinarazteko inprimakia erabiliz.</a> Inprimaki horretan, aipatu SQL errorearen kode hau:<br /><pre>$1</pre>',
  'highreplag' => 'Oharra: <a href=\'https://wiki.toolserver.org/view/Replag\'>Erreplikazioaren atzerapena</a> handia da. Duela $1 baino gutxiago egindako aldaketak beharbada ez dira agertuko.',
  'executed' => '$1 segundotan gauzatua',
  'translatelink' => 'itzuli',
  'w' => 'aste',
  'd' => 'egun',
  'h' => 'ordu',
  'm' => 'minutu',
  's' => 'segundo',
); ?>