<?php $_config_vars = array (
  'title' => 'uneltele lui X!',
  'source' => 'Vezi sursa',
  'language' => 'Selectați o limbă',
  'submit' => 'Trimite',
  'nowiki' => '$1 nu este un wiki valid',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Atenţie: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'executed' => 'Executed in $1 seconds',
  'translatelink' => 'translate',
  'w' => 'weeks',
  'd' => 'days',
  'h' => 'hours',
  'm' => 'minutes',
  's' => 'seconds',
); ?>