<?php $_config_vars = array (
  'title' => 'X!s verktøy',
  'source' => 'Vis kilde',
  'language' => 'Velg språk',
  'submit' => 'Gå',
  'nowiki' => '$1 er ikke en gyldig wiki',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL-feil, vennligst rapporter den til X! ved å bruke <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>feilrapporteringa</a>. Husk å ta med følgende feilmelding i rapporten:<br /><pre>$1</pre>',
  'highreplag' => 'Obs: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replikasjonstida</a> er høy, endringer som er nyere enn $1 vil ikke vises.',
  'executed' => 'Utført på $1 sekunder',
  'translatelink' => 'oversett',
  'w' => 'uker',
  'd' => 'dager',
  'h' => 'timer',
  'm' => 'minutter',
  's' => 'sekunder',
); ?>