<?php $_config_vars = array (
  'title' => 'X! के औजार',
  'source' => 'स्रोत देखें',
  'language' => 'भाषा चुनें',
  'submit' => 'जमा करें',
  'nowiki' => '$1 एक वैध विकि नहीं है।',
  'wiki' => 'विकि',
  'mysqlerror' => 'MySQL त्रुटि, कृपया <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'> बग रिपोर्टर का पुअयोग कर X! को सूचित करें।</a>निम्नलिखित SQL त्रुटि की जानकारी देते समय इसे अवश्य रिपोर्ट करें:<br /><pre>$1</pre>',
  'highreplag' => 'सावधानः <a href=\'https://wiki.toolserver.org/view/Replag\'>प्रतिकृति  अन्तराल</a> ऊँचा है, $1 से नए परिवर्तन हो सकता है कि ना दिखें।',
  'executed' => '$1 सेकिण्डों में निष्पादित',
  'translatelink' => 'अनुवाद',
  'w' => 'सप्ताह',
  'd' => 'दिन',
  'h' => 'घण्टे',
  'm' => 'मिनट',
  's' => 'सेकिण्ड',
); ?>