<?php $_config_vars = array (
  'title' => 'Ferramentas de X!',
  'source' => 'Ver código fonte',
  'language' => 'Selecciona unha linguaxe',
  'submit' => 'Enviar',
  'nowiki' => '$1 non é unha wiki válida',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'executed' => 'Executado en $1 segundos',
  'translatelink' => 'traducir',
  'w' => 'semanas',
  'd' => 'días',
  'h' => 'horas',
  'm' => 'minutos',
  's' => 'segundos',
); ?>