<?php $_config_vars = array (
  'title' => 'أدوات إكس!',
  'source' => 'شاهد المصدر',
  'language' => 'اختر لغة',
  'executed' => 'تم التنفيذ خلال $1 ثانية',
  'memory' => 'Taken $1 megabytes of memory to execute.',
  'submit' => 'قدّم',
  'nowiki' => '$1 ويكي غير صحيح',
  'bugs' => 'Bugs',
  'mysqlerror' => 'خطأ في قاعدة بيانات MySQL, الرجاء إعلام إكس! من خلال <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>المُعلم عن الخلل.</a> كن واثقا من من الإعلام بالخطأ التالي أثناء تقريرك:<br /><pre>$1</pre>',
  'highreplag' => 'تحذير: <a href=\'https://wiki.toolserver.org/view/Replag\'>هناك تأخير في النسخ المتماثل</a> بشكل كبير, ربما لا يتم عرض التغيرات الأحدث من $1.',
  'mo' => 'months',
  'w' => 'أسابيع',
  'd' => 'أيام',
  'h' => 'ساعات',
  'm' => 'دقائق',
  's' => 'ثواني',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'ويكي',
  'translatelink' => 'ترجم',
  'noexist' => '$1 does not exist',
); ?>