<?php $_config_vars = array (
  'title' => 'Ferramentas X!',
  'source' => 'Ver código',
  'language' => 'Selecione um idioma',
  'submit' => 'Enviar',
  'nowiki' => '$1 não é uma wiki válida',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Erro MySQL, por favor, reporte para X! usando <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>o reportador de erros.</a> Esteja certo de reportar o seguinte erro SQL:<br /><pre>$1</pre>',
  'highreplag' => 'Aviso: <a href=\'https://wiki.toolserver.org/view/Replag\'>O lag</a> está alto, mudanças mais recentes que $1 podem não ser exibidos.',
  'executed' => 'Executado em $1 segundos',
  'translatelink' => 'traduzir',
  'w' => 'semanas',
  'd' => 'dias',
  'h' => 'horas',
  'm' => 'minutos',
  's' => 'segundos',
); ?>