<?php $_config_vars = array (
  'title' => 'Outils de X!',
  'source' => 'Voir source',
  'language' => 'Sélectionnez une langue',
  'executed' => 'Exécuté en $1 secondes',
  'memory' => '$1 megabytes de mémoire utilisés pour l\'exécution. ',
  'submit' => 'Envoyer',
  'nowiki' => '$1 n\'est pas un wiki valide',
  'bugs' => 'Bugs',
  'mysqlerror' => 'Erreur MySQL, merci d\'informer X! sur <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>la page dédiée.</a> N\'oubliez pas d\'indiquer l\'erreur SQL suivante :<br /><pre>$1</pre>',
  'highreplag' => 'Attention : le <a href=\'https://wiki.toolserver.org/view/Replag\'>délai de réplication</a> est élevé, les modifications de moins de $1 ne sont pas prises en compte.',
  'mo' => 'mois',
  'w' => 'semaines',
  'd' => 'jours',
  'h' => 'heures',
  'm' => 'minutes',
  's' => 'secondes',
  'decimal_separator' => ',',
  'thousands_separator' => ' ',
  'wiki' => 'Wiki',
  'translatelink' => 'Traduisez',
); ?>