<?php $_config_vars = array (
  'title' => 'X! priemonės',
  'source' => 'Peržiūrėti išeities tekstą',
  'language' => 'Pasirinkti kalbą',
  'submit' => 'Siųsti',
  'nowiki' => '$1 nėra tikra viki',
  'wiki' => 'Viki',
  'mysqlerror' => 'MySQL klaida, prašom pranešti X! per <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>klaidų pranešimo puslapį.</a> Pranešdami būtinai nurodykite toliau pateiktą SQL klaidą:<br /><pre>$1</pre>',
  'highreplag' => 'Atsargiai: <a href=\'https://wiki.toolserver.org/view/Replag\'>replikavimo vėlinimas</a> didelis, pakeitimai, naujesni nei $1 gali būti nerodomi.',
  'executed' => 'Įvykdyta per $1 sekundžių',
  'translatelink' => 'išversti',
  'w' => 'savaitės',
  'd' => 'dienos',
  'h' => 'valandos',
  'm' => 'minutės',
  's' => 'sekundės',
); ?>