<?php $_config_vars = array (
  'title' => 'X!\'ගේ මෙවලම්',
  'source' => 'මූලාශ්‍රය පෙන්වන්න',
  'language' => 'භාෂාව තෝරන්න',
  'executed' => 'තත්පර $1 දී ක්‍රමලේඛිතයි',
  'memory' => 'මතකයෙන් මෙගාබයිට $1  ක් ක්‍රමලේඛණය සඳහා භාවිතා කෙරිණි.',
  'submit' => 'යවන්න',
  'nowiki' => '$1 වලංගු විකියක් නොවේ.',
  'bugs' => 'Bugs',
  'mysqlerror' => 'MySQL අර්බුදයකි, කරුණාකර <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre> භාවිතයෙන් X!‍ට වාර්තා කරන්න',
  'highreplag' => 'අවවාදය: <a href=\'https://wiki.toolserver.org/view/Replag\'>ප්‍රතිඋත්තර පමාව</a> වැඩියි, එනිසා $1 ට වැඩි සංස්කරණයන් දර්ශනය නොවනු ඇත.',
  'mo' => 'months',
  'w' => 'සති',
  'd' => 'දින',
  'h' => 'පැය',
  'm' => 'මිනිත්තු',
  's' => 'තත්පර',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'විකි',
  'translatelink' => 'පරිවර්තනය',
  'noexist' => '$1 අඩංගු නොවේ.',
); ?>