<?php $_config_vars = array (
  'title' => 'X!\'s iloj',
  'source' => 'Vidu fonton',
  'language' => 'elektu lingvon',
  'executed' => 'Ekzekutita en $1 sekundo(j).',
  'memory' => 'Prenis $1 megabajtojn da memoro por esti ekzekutita.',
  'submit' => 'Ek!',
  'nowiki' => '$1 ne estas valida vikio',
  'bugs' => 'Cimoj',
  'mysqlerror' => 'Eraro de MySQL, bonvolu raporti al X! per <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>cimraportilo.</a>. Certiĝu raporti la sekvantan SQL-eraron  :<br /><pre>$1</pre>',
  'highreplag' => 'Atentu! <a href=\'https://wiki.toolserver.org/view/Replag\'>kopia prokrasto</a> estas alta, ŝanĝoj okazintaj post $1 povas ne esti montritaj. ',
  'mo' => 'monatoj',
  'w' => 'semajnoj',
  'd' => 'tagoj',
  'h' => 'horoj',
  'm' => 'minutoj',
  's' => 'sekundoj',
  'decimal_separator' => ',',
  'thousands_separator' => ',',
  'wiki' => 'Vikio',
  'translatelink' => 'Traduku',
); ?>