<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'View Source',
  'language' => 'Choose a language',
  'submit' => 'Submit',
  'nowiki' => '$1 is not a valid wiki',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'executed' => 'Made in $1 seconds',
  'translatelink' => 'translate',
  'w' => 'weeks',
  'd' => 'days',
  'h' => 'hours',
  'm' => 'minutes',
  's' => 'seconds',
); ?>