<?php $_config_vars = array (
  'title' => 'X!\'s ツール！',
  'source' => 'ソースを見る',
  'language' => '言語を選択してください',
  'executed' => '$1秒で終了しました',
  'memory' => '実行には$1メガバイトのメモリー領域が必要です',
  'submit' => '投稿',
  'nowiki' => '$1というウィキは見つかりません',
  'bugs' => 'バグ',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Caution: <a href=\'https://wiki.toolserver.org/view/Replag\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'mo' => '月',
  'w' => '週',
  'd' => '日',
  'h' => '時間',
  'm' => '分',
  's' => '秒',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'ウィキ',
  'translatelink' => '翻訳',
  'noexist' => '$1は存在しません',
); ?>