<?php $_config_vars = array (
  'title' => 'Alat X!',
  'source' => 'Lihat Sumber',
  'language' => 'Pilih bahasa',
  'submit' => 'Kirim',
  'nowiki' => '$1 bukanlah wiki yang sah',
  'wiki' => 'Wiki',
  'mysqlerror' => 'Kesalahan MySQL, tolong laporkan ke X! menggunakan <a href=\'http://en.wikipedia.org/wiki/User:X!/Bugs\'>pelapor kesalahan.</a> Pastikan untuk melaporkan kesalahan SQL berikut ketika pelaporan: <br /><pre>$1</pre>',
  'highreplag' => 'Perhatian: <a href=\'https://wiki.toolserver.org/view/Replag\'>Lag replikasi</a> tinggi, perubahan lebih baru dari $1 dapat tidak ditampilkan.',
  'executed' => 'Dieksekusi dalam $1 detik',
  'translatelink' => 'terjemahkan',
  'w' => 'minggu',
  'd' => 'hari',
  'h' => 'jam',
  'm' => 'menit',
  's' => 'detik',
); ?>