<?php $_config_vars = array (
  'title' => 'بابەت',
  'source' => 'سەرچاوە',
  'language' => 'زمان',
  'submit' => 'ناردن',
  'nowiki' => '$1 is not a valid wiki',
  'wiki' => 'ویکی',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Caution: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Replication lag</a> is high, changes newer than $1 may not be shown.',
  'executed' => 'Executed in $1 seconds',
  'translatelink' => 'translate',
  'w' => 'weeks',
  'd' => 'days',
  'h' => 'hours',
  'm' => 'minutes',
  's' => 'seconds',
); ?>