<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'Quelltext betrachten',
  'language' => 'Sprache auswählen',
  'submit' => 'Absenden',
  'nowiki' => '$1 ist kein korrektes Wiki',
  'wiki' => 'Wiki',
  'mysqlerror' => 'MySQL Fehler, bitte an X! melden mit <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>dem Fehler-Melder.</a> Bitte sicher gehen, dass der folgende SQL Fehler genannt wird dabei:<br /><pre>$1</pre>',
  'highreplag' => 'Achtung: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Replag</a> ist hoch, Änderungen neuer als $1 werden nicht angezeigt.',
  'executed' => 'In $1 Sekunden ausgeführt',
  'translatelink' => 'Übersetzung',
  'w' => 'Wochen',
  'd' => 'Tage',
  'h' => 'Stunden',
  'm' => 'Minuten',
  's' => 'Sekunden',
); ?>