<?php $_config_vars = array (
  'title' => 'Narzędzia X!-a',
  'source' => 'Pokaż źródło',
  'language' => 'Wybierz język',
  'executed' => 'Wygenerowano w $1 sekund.',
  'memory' => 'Do wygenerowania użyto $1 megabajtów pamięci.',
  'submit' => 'Wyślij',
  'nowiki' => '$1 nie jest prawidłowym wikilinkiem',
  'bugs' => 'Bugi',
  'mysqlerror' => 'Błąd MySQL, proszę zgłosić do X!-a przy użyciu <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>tego narzędzia.</a> Należy się upewnić, że załączono zgłoszenie następującego błędu SQL:<br /><pre>$1</pre>',
  'highreplag' => 'Uwaga: <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>Replication lag</a> jest wysoki, zmiany nowsze niż $1 mogą nie być uwzględnione.',
  'mo' => 'miesiące',
  'w' => 'tygodnie',
  'd' => 'dni',
  'h' => 'godziny',
  'm' => 'minuty',
  's' => 'sekundy',
  'decimal_separator' => '.',
  'thousands_separator' => ' ',
  'wiki' => 'Wiki',
  'translatelink' => 'tłumacz',
  'noexist' => '$1 nie istnieje.',
); ?>