<?php $_config_vars = array (
  'title' => 'X!\'s tools',
  'source' => 'Просмотреть исходный код',
  'language' => 'Выберите язык:',
  'executed' => 'Выполнено за $1 с.',
  'memory' => 'Taken $1 megabytes of memory to execute.',
  'submit' => 'Отправить',
  'nowiki' => '$1 не существует',
  'bugs' => 'Ошибки',
  'mysqlerror' => 'MySQL error, please report to X! using <a href=\'//en.wikipedia.org/wiki/User:Cyberpower678\'>the bug reporter.</a> Be sure to report the following SQL error when reporting:<br /><pre>$1</pre>',
  'highreplag' => 'Предупреждаем, что ввиду отставания <a href=\'//ganglia.wmflabs.org/latest/?r=hour&cs=&ce=&c=tools&h=tools-login&tab=m&vn=&mc=2&z=medium&metric_group=NOGROUPS_|_Replication+Lags#mg_Replication_Lags\'>репликации БД</a>, правки новее $1 могут быть проигнорированы.',
  'mo' => 'месяцев',
  'w' => 'недель',
  'd' => 'дней',
  'h' => 'ч',
  'm' => 'мин',
  's' => 'с',
  'decimal_separator' => '.',
  'thousands_separator' => ',',
  'wiki' => 'Проект',
  'translatelink' => 'Перевести',
  'noexist' => '$1 does not exist',
); ?>